CREATE TABLE customer_order_notification (
  CUSTOMER_ORDER_NOTIFICATION_ID INT NOT NULL AUTO_INCREMENT,
  VISITORS_ACCOUNT_ID INT NOT NULL,
  BUSINESS_ORDER_ID INT NOT NULL,
  BUSINESS_ID INT NULL,
  EVENT_KEY VARCHAR(64) NOT NULL,
  NOTIFICATION_TYPE VARCHAR(30) NOT NULL,
  TITLE VARCHAR(150) NOT NULL,
  MESSAGE TEXT NULL,
  METADATA_JSON LONGTEXT NULL,
  IS_READ TINYINT NULL DEFAULT 0,
  CREATION_DATETIME DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (CUSTOMER_ORDER_NOTIFICATION_ID),
  UNIQUE KEY customer_order_notification_event_key (EVENT_KEY),
  KEY idx_customer_notification_visitor_read (VISITORS_ACCOUNT_ID, IS_READ),
  KEY idx_customer_notification_order (BUSINESS_ORDER_ID),
  KEY idx_customer_notification_created (CREATION_DATETIME)
);
